[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_fraction = "2FVnCxEJWcuxBVBZSphHPhLt3LyuXtbpDHubm4rXu1tP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "/Users/elvisyong/.config/solana/id.json"
wallet = "/home/abuba/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
